In [ ]:
#Creating Numpy Arrays
#Numpy arrays are like lists with extra functionality that are 

In [3]:
list1 = [1,2,3]
print(list1)

[1, 2, 3]


In [2]:
import numpy as np

In [4]:
numpy1 = np.array(list1)
print(numpy1)

[1 2 3]


In [5]:
#Prints out array of 5 zeros
#useful for initilizing an array with a prefault size
zerosArr = np.zeros(5)
print(zerosArr)

[0. 0. 0. 0. 0.]


In [7]:
#Same thing but with ones
onesArr = np.ones(10)
print(onesArr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [8]:
#Prints out a range array that stops before it reaches 5
rangeArr = np.arange(5)
print(rangeArr)

[0 1 2 3 4]


In [9]:
#Prints out a range array from 5 - 10 (exclusive)
rangeArr2 = np.arange(5, 11)
print(rangeArr2)

[ 5  6  7  8  9 10]


In [10]:
#Prints out a range array from 0 - 20 by twos
rangeArr3 = np.arange(0, 21, 2)
print(rangeArr3)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [11]:
#Prints an array from 0 - 10 (inclusive) with 5 indicies that are evenly spaced
#Default 3rd param is 50
linspaceArr = np.linspace(0, 10, 5)
print(linspaceArr)

[ 0.   2.5  5.   7.5 10. ]


In [12]:
#Default 3rd param is 50
linspaceArr2 = np.linspace(0, 10)
print(linspaceArr2)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
