In [1]:
#Creating Matricies in Numpy
import numpy as np

In [2]:
twoBytwo = np.matrix([[1,2],[3,4]])
print(twoBytwo)

[[1 2]
 [3 4]]


In [3]:
twoBythree = np.matrix([[1,2],[3,4],[5,6]])
print(twoBythree)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
#Having arrays with different lengths converts the arrays into lists
threeBytwha = np.matrix([[1,2],[3,4],[5,6,7]])
print(threeBytwha)

[[list([1, 2]) list([3, 4]) list([5, 6, 7])]]


In [6]:
#Prints same twoBythree matrix
twoBythree = np.matrix('1 2; 3 4; 5 6')
print(twoBythree)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
#Initiate a matrix [height, width]
#Height of 3, width of 2
print(np.zeros([3,2]))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [9]:
#Height of 2, width of 3
print(np.ones([2,3]))

[[1. 1. 1.]
 [1. 1. 1.]]
