In [1]:
#Numpy Modification Operations
#Operations to modify numpy arrays or the elements within

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,6)
print(arr)

[0 1 2 3 4 5]


In [4]:
#Modify first element of array
arr[0] = 10
print(arr)

[10  1  2  3  4  5]


In [5]:
#Reset array
arr = np.arange(0,6)
#Adds 6 to end of array
print(np.append(arr, 6))
#Adds 7 and 8 to end of array
print(np.append(arr, [7,8]))

[0 1 2 3 4 5 6]
[0 1 2 3 4 5 7 8]


In [7]:
#Insert 10 and 11 at index 1
print(np.insert(arr, 1, [10, 11]))

[ 0 10 11  1  2  3  4  5]


In [9]:
#Deletes element and shifts everything over
print(np.delete(arr, 3))

[0 2 3 4 5]


In [10]:
#Modify with operators
print(arr * 2)
print(arr % 2)
print(arr + 2) #etc.

[ 0  2  4  6  8 10]
[0 1 0 1 0 1]
[2 3 4 5 6 7]


In [13]:
#Sort array ASC
arr2 = np.array([3,6,21,10,5,1])
print(np.sort(arr2))

[ 1  3  5  6 10 21]


In [14]:
#Sort array DESC
#Multiplies array by -1 and sorts as ASC
print(np.sort(-arr2))
#Negate negative values to sort as DESC
print(-np.sort(-arr2))

[-21 -10  -6  -5  -3  -1]
[21 10  6  5  3  1]
