In [1]:
#Go over a quick example of matricies in action
import numpy as np

In [6]:
#Create an image of a I
img_mtrx = np.matrix('0 0 1 0 0; 0 0 1 0 0; 0 0 1 0 0; 0 0 1 0 0; 0 0 1 0 0')
print(img_mtrx)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [4]:
rows = img_mtrx.shape[0]
cols = img_mtrx.shape[1]
print(rows)
print(cols)

5
5


In [7]:
#Change black to white in I img
for row in range(rows):
    for col in range(cols):
        if img_mtrx[row, col] == 0:
            img_mtrx[row, col] = 1
        else:
            img_mtrx[row, col] = 0
print(img_mtrx)

[[1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]]


In [8]:
#Invert I image
#Transpose I img (rotates inverted I)
print(img_mtrx.T)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [9]:
#Flattens img
print(img_mtrx.flatten())

[[1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1]]
