In [1]:
#Functions to modify elements or properties of a matrix
import numpy as np

In [3]:
matrx = np.matrix('1 2; 3 4')
print(matrx)

[[1 2]
 [3 4]]


In [6]:
#Change one single element (3 -> 10)
#[height, width]
matrx[1, 0] = 10
print(matrx)

[[ 6  3]
 [10  4]]


In [5]:
#Change one entire row ([1,2] -> [6,3])
matrx[0] = [6, 3]
print(matrx)

[[ 6  3]
 [10  4]]


In [7]:
#Sort each row in ASC
print(np.sort(matrx))

[[ 3  6]
 [ 4 10]]


In [8]:
#Sort each row in DESC
print(-np.sort(-matrx))

[[ 6  3]
 [10  4]]


In [9]:
#Traspose operation (Cols to rows and rows to cols)
#Original
matrx = np.matrix('1 2; 3 4')
print(matrx)

[[1 2]
 [3 4]]


In [10]:
#Transposed [1,2] [3,4] -> [1,3] [2,4]
print(matrx.T)

[[1 3]
 [2 4]]


In [11]:
#Flatten matrix from x height to 1
#Ex. 2x2 -> 1x4
print(matrx.flatten())

[[1 2 3 4]]


In [12]:
#Use operaters on matricies
#Scalar multiplication
print(matrx * 2)

[[2 4]
 [6 8]]


In [13]:
#Use add function on matricies
#Matricies need to be the same shape
#Vector addition
print(np.add(matrx, matrx))

[[2 4]
 [6 8]]


In [14]:
#Matrix multiplication
#Common function used with matricies such as images
print(np.matmul(matrx, matrx))

[[ 7 10]
 [15 22]]
