In [1]:
#Numpy Fetch Operations

In [2]:
import numpy as np

In [3]:
#Create a numpy array
arr1 = np.arange(0, 11)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [5]:
first_element = arr1[0]
print(first_element)
last_element = arr1[10]
print(last_element)

0
10


In [11]:
first_five = arr1[0:5]
print(first_five)
first_five = arr1[:5]
print(first_five)

[0 1 2 3 4]
[0 1 2 3 4]


In [12]:
last_five = arr1[6:]
print(last_five)

[ 6  7  8  9 10]


In [13]:
#Using above array but striding by 2
#Called a stride length
last_five = arr1[6::2]
print(last_five)

[ 6  8 10]


In [15]:
#Striding by -1 results in counting down from the starting number (inclusive)
first_five_reversed = arr1[4::-1]
print(first_five_reversed)

[4 3 2 1 0]


In [16]:
final_two = arr1[-2:]
print(final_two)

[ 9 10]


In [17]:
#Length of array: use .size
print(arr1.size)

11


In [18]:
#Max: use np function np.amax()
print(np.amax(arr1))

10


In [19]:
#Min: use np function np.amin()
print(np.amin(arr1))

0


In [20]:
#Average: use np function np.average()
print(np.average(arr1))

5.0
