In [1]:
#Numpy Matrix Fetch Operations
import numpy as np

In [2]:
matrx = np.matrix('1 2 3; 4 5 6; 7 8 9')
print(matrx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
#Access single element (Ex. 4)
#Select row
print(matrx[1])

[[4 5 6]]


In [7]:
#Select column
print(matrx[1,0])

4


In [9]:
#Slice of arr within matrix
print(matrx[2, 1:3])

[[8 9]]


In [10]:
#Get size of matrix (total num of individual elements)
print(matrx.size)

9


In [11]:
#Get shape of matrix (tuple of height x width)
print(matrx.shape)

(3, 3)


In [12]:
#Max, min, avg
print(np.amax(matrx))
print(np.amin(matrx))
print(np.average(matrx))

9
1
5.0


In [13]:
#Max, min, avg (different syntax)
print(matrx.max())
print(matrx.min())
print(matrx.mean())

9
1
5.0
