In [1]:
#Explore what I have learned with thte practical example of a list of student grades

In [2]:
import numpy as np

In [5]:
#Create student grades array
student_grades = np.array([57,95,98,86,70,100,65,90,80,88])
print(student_grades)

[ 57  95  98  86  70 100  65  90  80  88]


In [6]:
#Get Avg
class_avg = np.average(student_grades)
print(class_avg)

82.9


In [7]:
#Get highest and lowest grades
highest_grade = np.amax(student_grades)
print(highest_grade)
lowest_grade = np.amin(student_grades)
print(lowest_grade)

100
57


In [8]:
#Get index of highest and lowest grades
#argmax and argmin used with machine learning
print(np.argmax(student_grades))
print(np.argmin(student_grades))

5
0


In [10]:
#Print grades in ASC and DESC orders
print(np.sort(student_grades))
print(-np.sort(-student_grades))

[ 57  65  70  80  86  88  90  95  98 100]
[100  98  95  90  88  86  80  70  65  57]


In [13]:
#Increase grades by 10% of the current grade
increase_grades = student_grades * 1.1
print(increase_grades)

[ 62.7 104.5 107.8  94.6  77.  110.   71.5  99.   88.   96.8]


In [14]:
#Increase grades by 10
increase_grades = student_grades + 10
print(increase_grades)

[ 62.7 104.5 107.8  94.6  77.  110.   71.5  99.   88.   96.8]


In [15]:
#Increase grades by 1
print(np.add(student_grades, np.ones(10)))

[ 58.  96.  99.  87.  71. 101.  66.  91.  81.  89.]


In [16]:
#Increase grades by the respective index
print(np.add(student_grades, np.array([1,2,3,4,5,6,7,8,9,10])))

[ 58  97 101  90  75 106  72  98  89  98]


In [ ]:
#Increase grades by the respective index
print(np.add(student_grades, np.ones(5)))